### ISSUE TITLE
从相册选取，直接进入了Hidden 照片集，Hidden照片集里没有照片

### ISSUE THREAD

**Issue by zhihaozhang** [Jonhory/JHUIImagePickerController-For-Swift#3]
如题，您的代码挺好用的，首先谢谢您。
但是我选择了从相册选取的话，会直接进入Hidden这个照片文件夹，我好想没有这个文件夹，是空的，我得首先左滑，然后才能选其他的文件夹。
![wechatimg237](https://user-images.githubusercontent.com/4500659/41093225-58df9c54-6a7d-11e8-84e0-0f39ad8ac7e6.jpeg)

左滑后才能选有照片的文件夹。

请问我如何能默认进入有照片的文件夹呢？
感谢，期待您的回复！

**Comment by Jonhory** [comment]
查看 JHImageListVC.swift 80行左右的代码，看截图你手机语言设置为非中文了，想要不出现 Hidden 文件夹，在一下判断时增加  item.localizedTitle == “Hidden" 即可
 
	    if item.localizedTitle == "最近删除" || item.localizedTitle == "已隐藏" {
                print("移除：",item.localizedTitle ?? "") 
                continue
            }
            // 移除 图片为空的相册
            if assetsFetchResult.count < 1 {
                print("移除图片为空：",item.localizedTitle ?? "")
                continue
            }

另外一个问题，想要默认进入 Recently Added  文件夹，在 JHImageListVC.swift 90行左右 ，有  // 将 所有照片 数据源放到顶部 的代码，

	    for item in items {
            if item.title == "所有照片" {//将这里的 所有照片 改为 “Recently Added” 或 “最近添加” 即可。
                if let index = items.index(where: { $0 == item } ) {
                    tempItem = item
                    items.remove(at: index)
                    break
                }
            }
        }


以上，希望能给你帮助。
